version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from Github
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m pip install poetry
            python3 -m poetry install
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            poetry run flake8 --statistics
            poetry run pytest -v --cov=calculator
